### PR TITLE
Split Shining Fates into 2 decks, matching tcg API

### PR DESCRIPTION
**Pull request by DeadMeme5441**
Swsh45 had 195 total pokemon - split it into swsh45 and swsh45sv, basically the normal cards and the shiny vault cards. This was done to match the main tcg api.

### CODE REVIEW

**Comment by DeadMeme5441** [comment]
I'll work on renaming the ID's of the pokemon - currently it says SWSH-74, instead of swsh-sv001 and so on.

**Comment by DeadMeme5441** [comment]
I've renamed the id and number fields to match the TCG main API. Not sure about set code, whether to keep it as swsh45 or convert to swsh45sv.

**Comment by kirbyUK** [comment]
Have you only done this for the `en-US` ones? Could you try and do the other languages too? It looks like you just used a script, so should be easy enough?

**Comment by DeadMeme5441** [comment]
Okay, I'll do it for the others as well no issues 👍🏻

**Comment by DeadMeme5441** [comment]
@kirbyUK Just finished all the languages, formatted the id and number as well.

**Comment by DeadMeme5441** [comment]
All files are ready to be merged I think, we're good to go.

**Pull request merged**
